### ISSUE TITLE
Alas! Boone County has changed their website.

### ISSUE THREAD

**Issue by sisiwei** [ireapps/first-web-scraper#10]
I'll try to carve out some time to go through the tutorial later today and update things, but now it's a Java site -- STILL WITH A TABLE! Just wanted to ping everyone and make sure you all knew. 

I have a former student going through the tutorial on her own and sending me questions as she goes, so I can probably take up the updating.

**Comment by palewire** [comment]
Missouri.

**Comment by michaelaharvey** [comment]
Making this change fixed it for me https://github.com/ireapps/first-web-scraper/pull/11

**Comment by hasibzunair** [comment]
Getting this error while following the documentation, any solution? @michaelaharvey 

`Traceback (most recent call last):
  File "rtd_scrap.py", line 31, in <module>
    writer.writerows(list_of_rows)
TypeError: a bytes-like object is required, not 'str'`
